### ISSUE TITLE
wordnet/linux/dict/* wird standardmäßig in der Codebase von Triple2NL gesucht 

### ISSUE THREAD

**Issue by dhaeb** [AKSW/SemWeb2NL#5]
Wordnet Wort-Datenbank Dateien können nicht aufgefunden werden, wenn Triple2NL per maven / jar im Projekt verwendet wird. Das Problem kann auf folgenen Code zurückgeführt werden (org/aksw/triple2nl/property/PropertyVerbalizer.java:86ff):
```java
if (wordnetDictionary == null) {
			try {
				File file = new File(PropertyVerbalizer.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath());
				file = new File(file, SystemUtils.IS_OS_WINDOWS ? "wordnet/windows/dict" : "wordnet/linux/dict");
				wordnetDictionary = file.getPath();
			} catch (URISyntaxException e) {
				e.printStackTrace();
			}
		}
```
Falls kein eigener Pfad zum Wordnet-Ordner angegeben wird, dient die "Codebase" (also der Pfad zu den class files z.B target/classes)  zum Auffinden des  Wordnet-Ordners. Dies funktioniert zur Entwicklungszeit, da der Ordner unkomprimiert zur Verfügung steht. Im Fall der Nutzung der Bibliothek als Abhängigkeit ist der Wordnet-Ordner jedoch in der Jar eingebettet und kann daher nicht vom Betriebssystem aufgefunden werden. 

Eine einfache Lösung wäre es, die benötigten Wordnet Dateien weiterhin in der jar mitzuführen und in den tmp Ordner des Nutzers zu kopieren bzw. den Pfad entsprechend anzupassen.

https://wordnet.princeton.edu/

**Comment by LorenzBuehmann** [comment]
We're using ExtJWNL now, which allows to load the WordNet dictionary via Maven dependency.
